#!/bin/bash
export JAVA_OPTS="-Dspecs2.color=false -Dsbt.log.format=true -Dsbt.log.noformat=true -Dhttp.proxyHost=127.0.0.1 -Dhttp.proxyPort=3128 $JAVA_OPTS" 
for step in clean test dist publish
do
        sbt -Dsbt.log.noformat=true -ivy $WORKSPACE ${step} || ( echo "Failure on ${step}" && exit 1 )
done
rm -rf target/*.rpm || ( echo "Error clearing TARGET" && exit 1 )
./rpm-build/jenkins_job_make_rpm || ( echo "Error generating RPM" && exit 1)
echo "Build OK"